In [ ]:
import torch

In [ ]:
random_t = torch.rand(3,3,4)

In [ ]:

random_t


tensor([[[0.2166, 0.6475, 0.9461, 0.9997],
         [0.9052, 0.4802, 0.5259, 0.9155],
         [0.6931, 0.0853, 0.6073, 0.3807]],

        [[0.7440, 0.0132, 0.5125, 0.2938],
         [0.7120, 0.0027, 0.3975, 0.6434],
         [0.8959, 0.0823, 0.5159, 0.4104]],

        [[0.2061, 0.7957, 0.8415, 0.5694],
         [0.2506, 0.1034, 0.9800, 0.0175],
         [0.8647, 0.3286, 0.9112, 0.2330]]])

In [ ]:
import numpy as np

In [ ]:
#A=np.array([[0,5,-10],[0,22,16],[0,-9,-2]])
A= np.array([[-5,-4,12]])
B= np.array([[-7,11,21]])

In [ ]:
A.shape

(1, 3)

In [ ]:


B=np.reshape(B, (-1, 1))

In [ ]:
B

array([[-7],
       [11],
       [21]])

In [ ]:
B.shape

(3, 1)

In [ ]:


C= B@A

In [ ]:

C

array([[  35,   28,  -84],
       [ -55,  -44,  132],
       [-105,  -84,  252]])

In [ ]:
C.shape

(3, 3)

In [ ]:

A_det = np.linalg.det(C)
print(A_det)

0.0


In [ ]:
A_det = np.linalg.eig(C)
print(A_det)

EigResult(eigenvalues=array([6.00000000e+00, 1.44247142e-15, 9.94529178e-16]), eigenvectors=array([[-0.26726124,  0.5971328 , -0.40454357],
       [ 0.53452248, -0.15634765, -0.16847086],
       [ 0.80178373,  0.7867578 , -0.8988671 ]]))


In [ ]:
type(C)

numpy.ndarray

In [ ]:
A_det

0.0

In [ ]:
A = np.array([[1,5,0], [0,10,0], [0,0,9]])
determinant = np.linalg.det(A)
print ('A = ', A)
print ('determinant of A= ', determinant)

A =  [[ 1  5  0]
 [ 0 10  0]
 [ 0  0  9]]
determinant of A=  90.0


In [ ]:
type(A)

numpy.ndarray

In [ ]:
A.shape

(3, 3)

In [ ]:
# Python program to illustrate functions
# can be treated as objects
def shout(text):
	return text.upper()

print(shout('Hello'))

yell = shout

print(yell('Hello'))


HELLO
HELLO


In [ ]:
# Python program to illustrate functions
# can be passed as arguments to other functions
def shout(text):
	return text.upper()

def whisper(text):
	return text.lower()

def greet(func):
	# storing the function in a variable
	greeting = func("""Hi, I am created by a function passed as an argument.""")
	print (greeting)

greet(shout)
greet(whisper)


HI, I AM CREATED BY A FUNCTION PASSED AS AN ARGUMENT.
hi, i am created by a function passed as an argument.


In [ ]:
def create_adder(x):
    def adder(y):
        return x+y

    return adder

add_15 = create_adder(15)

print(add_15(10))

In [ ]:
def hello_decorator(func):
	def inner1(*args, **kwargs):

		print("before Execution")

		# getting the returned value
		returned_value = func(*args, **kwargs)
		print("after Execution")

		# returning the value to the original frame
		return returned_value

	return inner1


# adding decorator to the function
@hello_decorator
def sum_two_numbers(a, b):
	print("Inside the function")
	return a + b

a, b,c = 1, 2,3

# getting the value through return of the function
print("Sum =", sum_two_numbers(a, b))


In [ ]:
import pandas as pd
import numpy as np
import asyncio
from concurrent.futures import ThreadPoolExecutor


In [ ]:
# Creating a sample DataFrame with millions of rows
df = pd.DataFrame(np.random.randn(1000000, 4), columns=list('ABCD'))


In [ ]:
df

A         B         C         D
0      -0.173538 -1.934072  0.557310 -1.971722
1       0.546098  0.821971  0.702940 -2.434507
2       0.799346  1.038003  1.035750 -0.685895
3      -0.032899  0.354039  0.635932 -0.350589
4      -0.259578 -0.584747  0.499165  1.447695
...          ...       ...       ...       ...
999995  1.043824  0.810522 -0.538627 -0.750818
999996  0.718927 -0.742768 -1.876215 -0.239531
999997 -1.231897 -0.411317  0.902101 -0.103540
999998  0.657124 -0.946900  0.400424 -2.426221
999999  0.603561 -0.720996  0.165720 -0.103938

[1000000 rows x 4 columns]

shashaseheh


```
# This is formatted as code
print('hello world")
```



In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('diabetes.csv')

In [ ]:
X = df.iloc[:-50,:-1]

In [ ]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
713            0      134             58             20      291  26.4   
714            3      102             74              0        0  29.5   
715            7      187             50             33      392  33.9   
716            3      173             78             39      185  33.8   
717           10       94             72             18        0  23.1   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
713                     0.352   21  
714                     0.121   32  
715                     0.826   34  
716                     0.970   31  
717                     0.595   56  

[718 rows x 8 columns]

In [ ]:
X = X[:].values


X.shape



(718, 8)

In [ ]:
y = df.iloc[:-50,-1]

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
713    0
714    0
715    1
716    1
717    0
Name: Outcome, Length: 718, dtype: int64

In [ ]:
y = y[:].values
y.shape



(718,)

In [ ]:
y = y.reshape((718, 1))

In [ ]:
len(df.columns)


785

In [ ]:
import numpy as np

weights_input_hidden1 = np.random.randn(X.shape[1],16)*0.1

bias_hidden1 = np.ones(shape=(1,16))

weights_hidden1_hidden2 = np.random.randn(16,32)*0.1

bias_hidden2 = np.ones(shape=(1,32))

weights_hidden2_output = np.random.randn(32,1)*0.1

bias_output = np.array([[0.1]])

learning_rate = 0.01

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def loss_function(predicted, actual):
    return -np.mean(actual * np.log(predicted) + (1 - actual) * np.log(1 - predicted))

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)



for epoch in range(10):
# Forward pass
  hidden1_input = np.dot(X, weights_input_hidden1) + bias_hidden1
  #print('the hidden one input is',hidden1_input, hidden1_input.shape)
  hidden1_output = relu(hidden1_input)
  #print('the hidden one output is',hidden1_output, hidden1_output.shape)

  hidden2_input = np.dot(hidden1_output, weights_hidden1_hidden2) + bias_hidden2
  #print('the hidden two input is',hidden2_input, hidden2_input.shape)
  hidden2_output = relu(hidden2_input)
  #print('the hidden two output is',hidden2_output, hidden2_output.shape)

  output_input = np.dot(hidden2_output, weights_hidden2_output) + bias_output
  #print('the output layer input is', output_input, output_input.shape)
  predicted_output = sigmoid(output_input)
  #print('the output predicted is', predicted_output, predicted_output.shape)

  loss = loss_function(predicted_output, y)
  #if epoch % 10 == 0:  # Print loss every 10 epochs
  print(f'Epoch {epoch+1}, Loss: {loss}')

  # Backward pass
  output_error = predicted_output-y
  #print('the output error is',output_error, output_error.shape)
  output_delta = output_error * sigmoid_derivative(predicted_output)
  #print('the output delta is', output_delta, output_delta.shape)

  hidden2_error = np.dot(output_delta, weights_hidden2_output.T)
  #print('the hidden two error is', hidden2_error, hidden2_error.shape)
  hidden2_delta = hidden2_error * relu_derivative(hidden2_output)
  #print('the hidden two delta is', hidden2_delta, hidden2_delta.shape)

  hidden1_error = np.dot(hidden2_delta, weights_hidden1_hidden2.T)
  #print('the hidden one error is', hidden1_error, hidden1_error.shape)
  hidden1_delta = hidden1_error * relu_derivative(hidden1_output)
  #print('the hidden one delta is', hidden1_delta, hidden1_delta.shape)

  # Update weights and biases
  #print('the weights from hidden2 to output before update is ', weights_hidden2_output)
  weights_hidden2_output += np.dot(hidden2_output.T, output_delta) * learning_rate
  #print('the weights from hidden2 to output after update is ', weights_hidden2_output)
  bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
  #print('the output bias values are', bias_output)

  #print('weights_hidden1_hidden2 before being are', weights_hidden1_hidden2)
  weights_hidden1_hidden2 += np.dot(hidden1_output.T, hidden2_delta) * learning_rate
  #print('weights_hidden1_hidden2 being updated are', weights_hidden1_hidden2)
  bias_hidden2 += np.sum(hidden2_delta, axis=0, keepdims=True) * learning_rate
  #print('the hidden2 bias values are', bias_hidden2)

  #print('weights_input_hidden1 before updated are', weights_input_hidden1)
  weights_input_hidden1 += np.dot(X.T, hidden1_delta) * learning_rate
  #print('weights_input_hidden1 after being updated are', weights_input_hidden1)
  bias_hidden1 += np.sum(hidden1_delta, axis=0, keepdims=True) * learning_rate
  #print('the hidden1 bias values are', bias_hidden1)



print("Updated weights and biases after one epoch:")
print("weights_input_hidden1:", weights_input_hidden1)
print("bias_hidden1:", bias_hidden1)
print("weights_hidden1_hidden2:", weights_hidden1_hidden2)
print("bias_hidden2:", bias_hidden2)
print("weights_hidden2_output:", weights_hidden2_output)
print("bias_output:", bias_output)


Epoch 1, Loss: 1.5658783990957856
Epoch 2, Loss: nan
Epoch 3, Loss: nan
Epoch 4, Loss: nan
Epoch 5, Loss: nan
Epoch 6, Loss: nan
Epoch 7, Loss: nan
Epoch 8, Loss: nan
Epoch 9, Loss: nan
Epoch 10, Loss: nan
Updated weights and biases after one epoch:
weights_input_hidden1: [[ 0.08997508  0.02985304 -0.18272255 -0.0312658   0.02798204 -0.06923455
   0.0737502   0.01477099 -0.17304814  0.08983972 -0.2318308  -0.05324246
   0.03801987  0.09311877 -0.19163315  0.03758341]
 [ 0.10040667 -1.09684715  0.38670621  0.13791548 -0.14443397 -0.15046804
   0.40905617  0.35160951 -0.89129755 -0.02184477  0.37628705 -0.17817813
  -0.24296967 -0.88693737 -0.73129018 -0.23124918]
 [ 0.27859754 -0.66316772  0.4049454   0.14764388  0.00847336 -0.04991218
   0.60217587  0.20852862 -0.58415162  0.24291168  0.30663771  0.11057997
  -0.1175899  -0.43270034 -0.46060407  0.0730286 ]
 [ 0.07955701 -0.14715376 -0.15238598  0.33636129  0.05144439 -0.10745894
  -0.19778839  0.09723429 -0.13416173 -0.12425467  0.099

<ipython-input-71-c92197d640a6>:18: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))
<ipython-input-71-c92197d640a6>:24: RuntimeWarning: divide by zero encountered in log
  return -np.mean(actual * np.log(predicted) + (1 - actual) * np.log(1 - predicted))
<ipython-input-71-c92197d640a6>:24: RuntimeWarning: invalid value encountered in multiply
  return -np.mean(actual * np.log(predicted) + (1 - actual) * np.log(1 - predicted))


In [ ]:
def prediction_normal(x):
    hidden1_input = np.dot(x, weights_input_hidden1) + bias_hidden1
    hidden1_output = relu(hidden1_input)
    print(hidden1_output.shape)

    hidden2_input = np.dot(hidden1_output, weights_hidden1_hidden2) + bias_hidden2
    hidden2_output = relu(hidden2_input)
    print(hidden2_output.shape)

    output_input = np.dot(hidden2_output, weights_hidden2_output) + bias_output
    predicted_output = sigmoid(output_input)


    return predicted_output

In [ ]:
print(prediction_normal([[0,123,72,0,0,36.3,0.258,52]]))

(1, 16)
(1, 32)
[[0.]]


<ipython-input-71-c92197d640a6>:18: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


In [ ]:
import numpy as np

# Initialize weights and biases
weights_input_hidden1 = np.random.randn(X.shape[1], 16) * 0.01
bias_hidden1 = np.ones(shape=(1, 16))

weights_hidden1_hidden2 = np.random.randn(16, 8) * 0.01
bias_hidden2 = np.ones(shape=(1, 8))

weights_hidden2_output = np.random.randn(8, 1) * 0.01
bias_output = np.array([[0.1]])

learning_rate = 0.01
batch_size = 32

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def loss_function(predicted, actual):
    return np.mean((actual - predicted) ** 2)

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

num_samples = X.shape[0]
indices = np.arange(num_samples)

for epoch in range(5):
    np.random.shuffle(indices)
    X_shuffled = X[indices]
    y_shuffled = y[indices]

    for i in range(0, num_samples, batch_size):
        X_batch = X_shuffled[i:i + batch_size]
        y_batch = y_shuffled[i:i + batch_size]

        # Forward pass
        hidden1_input = np.dot(X_batch, weights_input_hidden1) + bias_hidden1
        hidden1_output = relu(hidden1_input)

        hidden2_input = np.dot(hidden1_output, weights_hidden1_hidden2) + bias_hidden2
        hidden2_output = relu(hidden2_input)

        output_input = np.dot(hidden2_output, weights_hidden2_output) + bias_output
        predicted_output = sigmoid(output_input)

        loss = loss_function(predicted_output, y_batch)
        if i % (10 * batch_size) == 0:  # Print loss every 10 batches
            print(f'Epoch {epoch + 1}, Batch {i // batch_size + 1}, Loss: {loss}')

        # Backward pass
        output_error = predicted_output - y_batch
        output_delta = output_error * sigmoid_derivative(predicted_output)

        hidden2_error = np.dot(output_delta, weights_hidden2_output.T)
        hidden2_delta = hidden2_error * relu_derivative(hidden2_output)

        hidden1_error = np.dot(hidden2_delta, weights_hidden1_hidden2.T)
        hidden1_delta = hidden1_error * relu_derivative(hidden1_output)

        # Update weights and biases
        weights_hidden2_output += np.dot(hidden2_output.T, output_delta) * learning_rate / batch_size
        bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate / batch_size

        weights_hidden1_hidden2 += np.dot(hidden1_output.T, hidden2_delta) * learning_rate / batch_size
        bias_hidden2 += np.sum(hidden2_delta, axis=0, keepdims=True) * learning_rate / batch_size

        weights_input_hidden1 += np.dot(X_batch.T, hidden1_delta) * learning_rate / batch_size
        bias_hidden1 += np.sum(hidden1_delta, axis=0, keepdims=True) * learning_rate / batch_size


    # print("Updated weights and biases after one epoch:")
    # print("weights_input_hidden1:", weights_input_hidden1)
    # print("bias_hidden1:", bias_hidden1)
    # print("weights_hidden1_hidden2:", weights_hidden1_hidden2)
    # print("bias_hidden2:", bias_hidden2)
    # print("weights_hidden2_output:", weights_hidden2_output)
    # print("bias_output:", bias_output)


Epoch 1, Batch 1, Loss: 0.2572058070874109
Epoch 1, Batch 11, Loss: 0.263202106211629
Epoch 1, Batch 21, Loss: 0.27523650855878656
Epoch 2, Batch 1, Loss: 0.2728225206985505
Epoch 2, Batch 11, Loss: 0.27204214917220026
Epoch 2, Batch 21, Loss: 0.2729332473259131
Epoch 3, Batch 1, Loss: 0.2558400669172021
Epoch 3, Batch 11, Loss: 0.2805866419318157
Epoch 3, Batch 21, Loss: 0.30647403520457855
Epoch 4, Batch 1, Loss: 0.28319924467663815
Epoch 4, Batch 11, Loss: 0.31511898002215755
Epoch 4, Batch 21, Loss: 0.3177363463824331
Epoch 5, Batch 1, Loss: 0.29283420046279063
Epoch 5, Batch 11, Loss: 0.33044178580838784
Epoch 5, Batch 21, Loss: 0.37405325884271656


In [ ]:
sigmoid_derivative(predicted_output).shape

(768, 1)

In [ ]:
def prediction_sgd(x):
    hidden1_input = np.dot(x, weights_input_hidden1) + bias_hidden1
    hidden1_output = relu(hidden1_input)
    print(hidden1_output.shape)

    hidden2_input = np.dot(hidden1_output, weights_hidden1_hidden2) + bias_hidden2
    hidden2_output = relu(hidden2_input)
    print(hidden2_output.shape)

    output_input = np.dot(hidden2_output, weights_hidden2_output) + bias_output
    print(output_input)
    predicted_output = sigmoid(output_input)


    return predicted_output


In [ ]:
print(prediction_sgd([[6,190,92,0,0,35.5,0.278,66]]))

NameError: name 'prediction_sgd' is not defined

In [ ]:
z = np.ones(shape=(16,1))

In [ ]:
z

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:

print(np.dot(np.dot(np.dot(X,weights_input_hidden1)+ bias_hidden1, weights_hidden1_hidden2)+bias_hidden2, weights_hidden2_output)+bias_output)



In [ ]:
import numpy as np

class NeuralNetwork:
    def __init__(self, input_size, hidden1_size, hidden2_size, output_size):
        self.input_size = input_size
        self.hidden1_size = hidden1_size
        self.hidden2_size = hidden2_size
        self.output_size = output_size

        # Initialize weights
        self.weights_input_hidden = np.random.randn(self.input_size, self.hidden1_size) * np.sqrt(2. / self.input_size)
        self.weights_hidden1_hidden2 = np.random.randn(self.hidden1_size, self.hidden2_size) * np.sqrt(2. / self.hidden1_size)

        self.weights_hidden2_output = np.random.randn(self.hidden2_size, self.output_size) * np.sqrt(2. / self.hidden2_size)

        # Initialize the biases
        self.bias_hidden1 = np.zeros((1, self.hidden1_size))
        self.bias_hidden2 = np.zeros((1, self.hidden2_size))
        self.bias_output = np.zeros((1, self.output_size))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def feedforward(self, X):
        # Input to hidden
        self.hidden1_activation = np.dot(X, self.weights_input_hidden) + self.bias_hidden1
        self.hidden1_output = self.sigmoid(self.hidden1_activation)

        # Hidden1 to hidden2
        self.hidden2_activation = np.dot(self.hidden1_output, self.weights_hidden1_hidden2) + self.bias_hidden2
        self.hidden2_output = self.sigmoid(self.hidden2_activation)

        # Hidden to output
        self.output_activation = np.dot(self.hidden2_output, self.weights_hidden2_output) + self.bias_output
        self.predicted_output = self.sigmoid(self.output_activation)

        return self.predicted_output

    def backward(self, X, y, learning_rate):
        # Compute the output layer error
        output_error = y - self.predicted_output
        output_delta = output_error * self.sigmoid_derivative(self.predicted_output)

        # Compute the hidden2 layer error
        hidden2_error = np.dot(output_delta, self.weights_hidden2_output.T)
        hidden2_delta = hidden2_error * self.sigmoid_derivative(self.hidden2_output)

        # Compute the hidden1 layer error
        hidden1_error = np.dot(hidden2_delta, self.weights_hidden1_hidden2.T)
        hidden1_delta = hidden1_error * self.sigmoid_derivative(self.hidden1_output)

        # Update weights and biases
        self.weights_hidden2_output += np.dot(self.hidden2_output.T, output_delta) * learning_rate
        self.bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate

        self.weights_hidden1_hidden2 += np.dot(self.hidden1_output.T, hidden2_delta) * learning_rate
        self.bias_hidden2 += np.sum(hidden2_delta, axis=0, keepdims=True) * learning_rate

        self.weights_input_hidden += np.dot(X.T, hidden1_delta) * learning_rate
        self.bias_hidden1 += np.sum(hidden1_delta, axis=0, keepdims=True) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            output = self.feedforward(X)
            self.backward(X, y, learning_rate)
            if epoch % 10 == 0:
                loss = np.mean(np.square(y - output))
                print(f"Epoch {epoch}, Loss: {loss}")

# Example usage:
# Assuming X and y are defined elsewhere
# X should be the input data matrix
# y should be the target output vector/matrix
# For example:
# X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# y = np.array([[0], [1], [1], [0]])

nn = NeuralNetwork(input_size=8, hidden1_size=32, hidden2_size=16, output_size=1)
nn.train(X, y, epochs=100, learning_rate=0.001)

# Test the trained model
output = nn.feedforward([[1,126,60,0,0,30.1,0.349,47]])
print("Predictions after training:")
print(output)


Epoch 0, Loss: 0.24364786706132832
Epoch 10, Loss: 0.2285584494108692
Epoch 20, Loss: 0.22572451165838914
Epoch 30, Loss: 0.22374879933465486
Epoch 40, Loss: 0.22239372350984168
Epoch 50, Loss: 0.22128142159230166
Epoch 60, Loss: 0.22027178803436176
Epoch 70, Loss: 0.21931707562851138
Epoch 80, Loss: 0.2183775628089821
Epoch 90, Loss: 0.21748132966709466
Predictions after training:
[[0.40857764]]


In [ ]:
import numpy as np

class NeuralNetwork:
    def __init__(self, input_size, hidden1_size, hidden2_size, output_size):
        self.input_size = input_size
        self.hidden1_size = hidden1_size
        self.hidden2_size = hidden2_size
        self.output_size = output_size

        # Initialize weights with He initialization
        self.weights_input_hidden = np.random.randn(self.input_size, self.hidden1_size) * np.sqrt(2. / self.input_size)
        self.weights_hidden1_hidden2 = np.random.randn(self.hidden1_size, self.hidden2_size) * np.sqrt(2. / self.hidden1_size)
        self.weights_hidden2_output = np.random.randn(self.hidden2_size, self.output_size) * np.sqrt(2. / self.hidden2_size)

        # Initialize the biases
        self.bias_hidden1 = np.zeros((1, self.hidden1_size))
        self.bias_hidden2 = np.zeros((1, self.hidden2_size))
        self.bias_output = np.zeros((1, self.output_size))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def relu(self, x):
        return np.maximum(0, x)

    def relu_derivative(self, x):
        return np.where(x > 0, 1, 0)

    def binary_cross_entropy(self, predicted, actual):
        epsilon = 1e-12  # to prevent log(0)
        predicted = np.clip(predicted, epsilon, 1. - epsilon)
        return -np.mean(actual * np.log(predicted) + (1 - actual) * np.log(1 - predicted))

    def feedforward(self, X):
        # Input to hidden1
        self.hidden1_activation = np.dot(X, self.weights_input_hidden) + self.bias_hidden1
        self.hidden1_output = self.relu(self.hidden1_activation)

        # Hidden1 to hidden2
        self.hidden2_activation = np.dot(self.hidden1_output, self.weights_hidden1_hidden2) + self.bias_hidden2
        self.hidden2_output = self.relu(self.hidden2_activation)

        # Hidden2 to output
        self.output_activation = np.dot(self.hidden2_output, self.weights_hidden2_output) + self.bias_output
        self.predicted_output = self.sigmoid(self.output_activation)

        return self.predicted_output

    def backward(self, X, y, learning_rate):
        # Compute the output layer error
        output_error = self.predicted_output - y
        output_delta = output_error * self.sigmoid_derivative(self.predicted_output)

        # Compute the hidden2 layer error
        hidden2_error = np.dot(output_delta, self.weights_hidden2_output.T)
        hidden2_delta = hidden2_error * self.relu_derivative(self.hidden2_output)

        # Compute the hidden1 layer error
        hidden1_error = np.dot(hidden2_delta, self.weights_hidden1_hidden2.T)
        hidden1_delta = hidden1_error * self.relu_derivative(self.hidden1_output)

        # Update weights and biases
        self.weights_hidden2_output += np.dot(self.hidden2_output.T, output_delta) * learning_rate
        self.bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate

        self.weights_hidden1_hidden2 += np.dot(self.hidden1_output.T, hidden2_delta) * learning_rate
        self.bias_hidden2 += np.sum(hidden2_delta, axis=0, keepdims=True) * learning_rate

        self.weights_input_hidden += np.dot(X.T, hidden1_delta) * learning_rate
        self.bias_hidden1 += np.sum(hidden1_delta, axis=0, keepdims=True) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            output = self.feedforward(X)
            self.backward(X, y, learning_rate)
            if epoch % 100 == 0:
                loss = self.binary_cross_entropy(output, y)
                print(f"Epoch {epoch}, Loss: {loss}")

# Example usage:
# Assuming X and y are defined elsewhere
# X should be the input data matrix
# y should be the target output vector/matrix
# For example:
# X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# y = np.array([[0], [1], [1], [0]])

# Normalize input data
X = (X - np.min(X)) / (np.max(X) - np.min(X))

nn = NeuralNetwork(input_size=8, hidden1_size=32, hidden2_size=16, output_size=1)
nn.train(X, y, epochs=1000, learning_rate=0.01)

# Test the trained model
output = nn.feedforward(np.array([[1,126,60,0,0,30.1,0.349,47]]))
print("Predictions after training:")
print(output)


Epoch 0, Loss: 0.7060554093717362
Epoch 100, Loss: 6.497219400295372
Epoch 200, Loss: 7.0348464217233975
Epoch 300, Loss: 7.346227684998566
Epoch 400, Loss: 7.565904772092636
Epoch 500, Loss: 7.7356292527089865
Epoch 600, Loss: 7.873884296395813
Epoch 700, Loss: 7.990492371476175
Epoch 800, Loss: 8.09129857683994
Epoch 900, Loss: 8.180062448569068
Predictions after training:
[[1.]]


In [ ]:
import numpy as np

class NeuralNetwork:
    def __init__(self, input_size, hidden1_size, hidden2_size, output_size):
        self.input_size = input_size
        self.hidden1_size = hidden1_size
        self.hidden2_size = hidden2_size
        self.output_size = output_size

        # Initialize weights with He initialization
        self.weights_input_hidden = np.random.randn(self.input_size, self.hidden1_size) * np.sqrt(2. / self.input_size)
        self.weights_hidden1_hidden2 = np.random.randn(self.hidden1_size, self.hidden2_size) * np.sqrt(2. / self.hidden1_size)
        self.weights_hidden2_output = np.random.randn(self.hidden2_size, self.output_size) * np.sqrt(2. / self.hidden2_size)

        # Initialize the biases
        self.bias_hidden1 = np.zeros((1, self.hidden1_size))
        self.bias_hidden2 = np.zeros((1, self.hidden2_size))
        self.bias_output = np.zeros((1, self.output_size))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def relu(self, x):
        return np.maximum(0, x)

    def relu_derivative(self, x):
        return np.where(x > 0, 1, 0)

    def binary_cross_entropy(self, predicted, actual):
        epsilon = 1e-12  # to prevent log(0)
        predicted = np.clip(predicted, epsilon, 1. - epsilon)
        return -np.mean(actual * np.log(predicted) + (1 - actual) * np.log(1 - predicted))

    def feedforward(self, X):
        # Input to hidden1
        self.hidden1_activation = np.dot(X, self.weights_input_hidden) + self.bias_hidden1
        self.hidden1_output = self.relu(self.hidden1_activation)

        # Hidden1 to hidden2
        self.hidden2_activation = np.dot(self.hidden1_output, self.weights_hidden1_hidden2) + self.bias_hidden2
        self.hidden2_output = self.relu(self.hidden2_activation)

        # Hidden2 to output
        self.output_activation = np.dot(self.hidden2_output, self.weights_hidden2_output) + self.bias_output
        self.predicted_output = self.sigmoid(self.output_activation)

        return self.predicted_output

    def backward(self, X, y, learning_rate):
        # Compute the output layer error
        output_error = self.predicted_output - y
        output_delta = output_error * self.sigmoid_derivative(self.predicted_output)

        # Compute the hidden2 layer error
        hidden2_error = np.dot(output_delta, self.weights_hidden2_output.T)
        hidden2_delta = hidden2_error * self.relu_derivative(self.hidden2_output)

        # Compute the hidden1 layer error
        hidden1_error = np.dot(hidden2_delta, self.weights_hidden1_hidden2.T)
        hidden1_delta = hidden1_error * self.relu_derivative(self.hidden1_output)

        # Update weights and biases
        self.weights_hidden2_output -= np.dot(self.hidden2_output.T, output_delta) * learning_rate
        self.bias_output -= np.sum(output_delta, axis=0, keepdims=True) * learning_rate

        self.weights_hidden1_hidden2 -= np.dot(self.hidden1_output.T, hidden2_delta) * learning_rate
        self.bias_hidden2 -= np.sum(hidden2_delta, axis=0, keepdims=True) * learning_rate

        self.weights_input_hidden -= np.dot(X.T, hidden1_delta) * learning_rate
        self.bias_hidden1 -= np.sum(hidden1_delta, axis=0, keepdims=True) * learning_rate

    def train(self, X, y, epochs, learning_rate):
        for epoch in range(epochs):
            output = self.feedforward(X)
            self.backward(X, y, learning_rate)
            if epoch % 100 == 0:
                loss = self.binary_cross_entropy(output, y)
                print(f"Epoch {epoch}, Loss: {loss}")

# Example usage:
# Assuming X and y are defined elsewhere
# X should be the input data matrix
# y should be the target output vector/matrix
# For example:
# X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# y = np.array([[0], [1], [1], [0]])

# Normalize input data
X = (X - np.min(X)) / (np.max(X) - np.min(X))

nn = NeuralNetwork(input_size=8, hidden1_size=32, hidden2_size=16, output_size=1)
nn.train(X, y, epochs=10, learning_rate=0.001)

# Test the trained model
output = nn.feedforward(np.array([[1,126,60,0,0,30.1,0.349,47]]))
print("Predictions after training:")
print(output)


Epoch 0, Loss: 0.6923671466348617
Predictions after training:
[[9.10868244e-08]]
